export const RESTART_CREATE_MAIL_RESPONSE = "RESTART_CREATE_MAIL_RESPONSE";

export const CREATE_MAIL_LOADING = "CREATE_MAIL_LOADING";

export const CREATE_MAIL_SUCCESS = "CREATE_MAIL_SUCCESS";

export const CREATE_MAIL_ERROR = "CREATE_MAIL_ERROR";

export const CREATE_MAIL_CODE_ERROR = "CREATE_CODE_ERROR";

export const RESTART_VIEW_MAILS_RESPONSE = "RESTART_VIEW_MAILS_RESPONSE";

export const VIEW_MAILS_LOADING = "VIEW_MAILS_LOADING";

export const VIEW_MAILS_SUCCESS = "VIEW_MAILS_SUCCESS";

export const VIEW_MAILS_ERROR = "VIEW_MAILS_ERROR";

export const VIEW_MAILS_CODE_ERROR = "VIEW_MAILS_ERROR";

export const VIEW_MAILS_FILTER_MODAL = "VIEW_MAIL_FILTER_MODAL";

export const HIDE_MAIL_FILTER_MODAL = "HIDE_MAIL_FILTER_MODAL";





